const imageData = ["image/weaponspeed.png",
"image/white.jpg",
"image/zanki.png",
"image/4way.png",
"image/alert.jpg",
"image/ATARI B.png",
"image/ATARI.png",
"image/background.jpg",
"image/background2.jpg",
"image/backgroundnight.jpg",
"image/BENEMY.png",
"image/BENEMY1.png",
"image/BENEMY2.png",
"image/black.jpg",
"image/CENEMY1.png",
"image/CENEMY1R.png",
"image/CENEMY2.png",
"image/CENEMY3.png",
"image/CENEMYL.png",
"image/CENEMYR.png",
"image/credits.jpg",
"image/DEFEAT_PLAYER0.png",
"image/DEFEAT_PLAYER1.png",
"image/DEFEAT_PLAYER2.png",
"image/DEFEAT_PLAYER3.png",
"image/DEFEAT_PLAYER4.png",
"image/DEFEAT_PLAYER5.png",
"image/DENEMY.png",
"image/DENEMY1.png",
"image/DENEMY2.png",
"image/DENEMY3.png",
"image/down.png",
"image/down_anim.png",
"image/downA.png",
"image/downB.png",
"image/EENEMY.png",
"image/EENEMY1.png",
"image/EENEMY2.png",
"image/EENEMY3.png",
"image/EENEMY4.png",
"image/ENEMY.png",
"image/ENEMY_A.png",
"image/enemy_anim.png",
"image/ENEMY_B.png",
"image/ENEMYD.png",
"image/enemyD_anim.png",
"image/ENEMYD2.png",
"image/ENEMYD3.png",
"image/enteralert.png",
"image/enteralert1.png",
"image/enteralert2.png",
"image/erase_0.png",
"image/erase_1.png",
"image/erase_2.png",
"image/erase_screen.jpg",
"image/esc.png",
"image/favicon.ico",
"image/favicon.png",
"image/gameover.jpg",
"image/gameover_continue.jpg",
"image/gameover_continue1.png",
"image/gameover_continue2.png",
"image/gameover_continue2-1.png",
"image/gameover_continue2-2.png",
"image/gameover_continue3.png",
"image/heart.png",
"image/IDOL.png",
"image/IDOL1.png",
"image/IDOL2.png",
"image/IDOL3.png",
"image/IDOL4.png",
"image/item.png",
"image/left.png",
"image/left_anim.png",
"image/leftA.png",
"image/leftB.png",
"image/logo.png",
"image/maple.png",
"image/maple_night.png",
"image/miss_anim.png",
"image/missdown.png",
"image/missleft.png",
"image/missright.png",
"image/mode_A.png",
"image/mode_B.png",
"image/page1.jpg",
"image/page2.jpg",
"image/page3.jpg",
"image/page4.jpg",
"image/page5.jpg",
"image/page6.jpg",
"image/page7.jpg",
"image/page8.jpg",
"image/page100.jpg",
"image/page101.jpg",
"image/pause.png",
"image/pause1.png",
"image/pause2.png",
"image/PUSHENTER.png",
"image/PUSHENTER1.png",
"image/PUSHENTER2.png",
"image/right.png",
"image/right_anim.png",
"image/RunningError.jpg",
"image/screen.png",
"image/ScriptError.jpg",
"image/size_alert.jpg",
"image/sound.jpg",
"image/speed.png",
"image/status.png",
"image/title.jpg",
"image/title.png",
"image/titlenight.jpg",
"image/up.png",
"image/up_anim.png",
"image/upA.png",
"image/upB.png",
"image/weapon.png",
"image/weapon_anim.png",
"image/weaponA.png",
"image/weaponB.png",
"image/weaponC.png"];


for(let i = 0; i < imageData.length; i++){
    
 document.write( "<div id= loading"+i+"> </div>" );
document.getElementById( "loading"+i ).style.position = "absolute";
document.getElementById( "loading"+i ).style.left = i;
document.getElementById( "loading"+i ).style.top = i;
    document.getElementById( "loading"+i ).style.opacity = 0;
    document.getElementById( "loading"+i ).style.zIndex = -10000;
document.getElementById( "loading"+i ).innerHTML = "";
    document.getElementById( "loading"+i ).style.transform = "scale(10%)";
        screen.appendChild(document.getElementById( "loading"+i ));
}

function loadElements(){
    
    for(let i = 0; i < imageData.length; i++){
    setImage(document.getElementById( "loading"+i ),imageData[i]);
    }
        
}

loadElements();